spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.0.184:8066/TESTDB?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis:
    type-aliases-package: com.haiyu.entity
    mapper-locations: classpath:mapper/*.xml

